device = "cuda:1"
do_train = true
do_pretrain = true
bimamba_type = "none"
distributed = true
MLM = true
MVC = true
TOPO = true
run_name = "emb_10k_human_lung"
graph_sort = true
random_sort = false
generative_pretraining = true
only_value_emb = false
alpha_mlm = 0.1
alpha_topo = 1
alpha_mvc = 0.5
epochs = 5
test_size = 0.2
lr = 0.0001
seed = 42
dropout = 0.2
batch_size = 64
layer_size = 512
nlayers = 10
mask_ratio = 0
pre_norm = false
freeze = false
log_interval = 100
save_eval_interval = 1
schedule_ratio = 0.9
amp = true
token_emb_freeze = false
sampling_etype = "ori"
layer_mask = false
layer_emb = true
save_dir = "/home/share/huadjyin/home/s_huluni/project/RegFormer/gzh/tutorials/cell_emb/saves"
vocab_file = "/home/share/huadjyin/home/s_huluni/project/RegFormer/case/graph/data/vocab/vocab.json"
graph_path = "/home/share/huadjyin/home/s_huluni/project/RegFormer/case/graph/out/cistarget_top20/output_graph_no_cycles.dgl"
cell_type_column = "cell_type"
batch_column = ""
gene_column = "none"
umap_column = "none"
pca_column = "none"
data_is_raw = false
filter_gene_by_counts = false
DSBN = false
input_emb_style = "continuous"
cell_emb_style = "avg-pool"
mvc_decoder_style = "inner product"
n_bins = 51
append_cls = false
per_seq_batch_sample = false
include_zero_gene = false
input_style = "binned"
output_style = "binned"
max_seq_len = 10000
model_name = "RegFormer-1.2k"
data_name = "human_lung"
data_path = "/home/share/huadjyin/home/s_huluni/project/RegFormer/case/03_cell_emb/data/human_lung.h5ad"
load_model = "/home/share/huadjyin/home/s_huluni/project/RegFormer/case/02_pretrain/models/Pretraining/cellxgene/mamba/pt_graph_sort_avg_pool_all_length"
n_hvg = 3000