task='Cell_annotation'
bimamba_type='none'     #type of bimamba: ['v1','v2','none']
distributed=false   #current script is unavailable for distributed training, always set to false plz
MLM=false   #whether to use masked language modeling
CCE=false   #contrastive cell embedding objective
CLS=false    #celltype classification objective
cls_weight=false #using different weights for different classes during loss bp
TOPO=false
MVC=false

do_pretrain=true
do_train=true

run_name = "grn_10k_huamn_lung"
graph_sort = true
random_sort = false
generative_pretraining = true
only_value_emb = false
alpha_mlm = 0.1
alpha_topo = 1
alpha_mvc = 0.5
nlayers_cls=1
epochs = 10
test_size = 0.2
lr = 1e-4
seed = 42
dropout = 0.2
batch_size = 8
layer_size = 512
nlayers = 10
mask_ratio = 0
pre_norm = false
freeze = false
log_interval = 100
save_eval_interval = 1
schedule_ratio = 1
amp = true
token_emb_freeze = false
sampling_etype = "ori"
layer_mask = false
layer_emb = false
save_dir = "/home/share/huadjyin/home/s_huluni/gzh/RegFormer/case/tutorials/grn/saves"
vocab_file = "/home/share/huadjyin/home/s_huluni/project/RegFormer/case/graph/data/vocab/vocab.json"
graph_path = "/home/share/huadjyin/home/s_huluni/project/RegFormer/case/graph/out/cistarget_top20/output_graph_no_cycles.dgl"
gene_sets='/home/share/huadjyin/home/s_huluni/project/RegFormer/case/ablation/bin/grn/c5.go.bp.v2025.1.Hs.symbols.gmt'
tf_file="/home/share/huadjyin/home/s_huluni/chenqianqian/files_for_pyscenic/resources/hs_hgnc_tfs.txt"
cell_type_column = "cell_type"
batch_column = ""
num_batch_labels="none"
gene_column = "none"
umap_column = "none"
pca_column = "none"
data_is_raw = false
filter_gene_by_counts=3
DSBN = false
input_emb_style = "continuous"
cell_emb_style = "avg-pool"
mvc_decoder_style = "inner product"
n_bins = 51
append_cls = false
per_seq_batch_sample = false
include_zero_gene = false
input_style = "binned"
output_style = "binned"
max_seq_len =10000
n_hvg=-1
model_name = "RegFormer-10k"
data_name = "human_lung"
data_path = "/home/share/huadjyin/home/s_huluni/project/RegFormer/case/05_grn/data/human_lung.h5ad"
load_model = "/home/share/huadjyin/home/s_huluni/project/RegFormer/case/02_pretrain/models/Pretraining/cellxgene/mamba/pt_graph_sort_avg_pool_all_length"
device = "cuda"