task='Pretraining'
data_name='cellxgene'   #['panglao','cellxgene']
model_name = "mamba"    #['gpt','mamba','bimamba']
do_train=true   #Train or inference
bimamba_type='none'     #type of bimamba: ['v1','v2','none']
distributed=true   #current script is unavailable for distributed training, always set to false plz
MLM=true   #whether to use masked language modeling, for the value prediction
MVC=false   #contrastive cell embedding objective

# ablation params
run_name='ablation_value_embedding_graph_sort_continue'    #name of experiment.
graph_sort=true     #using graph topological sorting
random_sort=false
generative_pretraining=true    #using generative token precidtion in pretraining or masked token prediction in pretraining
only_value_emb=true  # using single embedding for value prediction, for the ablation study

epochs=2
test_size=0.2
lr=1e-4
seed=42
dropout=0.2
batch_size=8
layer_size=256
nlayers=4
nhead=4
mask_ratio=0.4
pre_norm=false  #normalize previously
freeze=false    #freeze the backbone during finetuning
log_interval=100
save_eval_interval=1
schedule_ratio=0.9      #ratio of epochs for learning rate schedule
amp=true    #Automatic Mixed Precision
token_emb_freeze=false      #freezing token-emb when predicting value
sampling_etype='ori'     #choice of edge type when sampling: ['share_pathway_with','interact_with','co_expression','ori']
layer_mask=false        #using layer mask or not when using graph sort
layer_emb=true         # using layer emb or not when using graph sort

#######dir
data_path='/home/share/huadjyin/home/s_qiuping1/workspace/RegFormer/example/data'
load_model='/home/share/huadjyin/home/s_qiuping1/workspace/RegFormer/example/model/pt/Pretraining/cellxgene/mamba/ablation_value_embedding_graph_sort/'    #from_scratch: false
save_dir='/home/share/huadjyin/home/s_qiuping1/workspace/RegFormer/example/model/pt'  #Directory of checkpoint and result to save
vocab_file='/home/share/huadjyin/home/s_qiuping1/workspace/RegFormer/example/data/vocab.json'
graph_path='/home/share/huadjyin/home/s_qiuping1/workspace/RegFormer/example/data/graph'
lmdb=true       # use lmdb dataset or not
lmdb_path='/home/share/huadjyin/home/s_qiuping1/workspace/RegFormer/example/data/lmdb/train.db' #Path of source lmdb&h5ad data
val_lmdb_path='/home/share/huadjyin/home/s_qiuping1/workspace/RegFormer/example/data/lmdb/val.db' #Path of source lmdb&h5ad data

#######data config
cell_type_column='celltype'
batch_column='batch'
gene_column='none'  #set to "none" or specific column-name based on your requirement
umap_column='none'    #set to "none" or specific column-name based on your requirement
pca_column='none'      #set to "none" or specific column-name based on your requirement
data_is_raw=false
filter_gene_by_counts=false
DSBN=false

input_emb_style='continuous'    #the style of input emb：['continuous','category','scaling']
cell_emb_style='attn'   #method for generating cell emb: ['final','cls','avg-pool','w-pol','attn']
mvc_decoder_style='inner product'   #architecture style of the decoder:['inner product','concat query','sum query']
n_bins=51
append_cls=false    #append <cls> token as first token
per_seq_batch_sample=false      #whether sort the adata by batch_id
include_zero_gene=false     #whether include gene with zero expression value
input_style='binned'       #input representation: ['binned','normed_raw','log1p']
output_style='binned'       #output representation: ['binned','normed_raw','log1p']
max_seq_len=1200
